# Generated by Django 4.2.19 on 2025-04-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DESD_App", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
