# Generated by Django 5.1.3 on 2025-04-30 18:03

from django.db import migrations


def delete_all_data(apps, schema_editor):
    """Delete all data from the tables we're going to remove"""
    ModelPerformance = apps.get_model('DESD_App', 'ModelPerformance')
    ModelUpdate = apps.get_model('DESD_App', 'ModelUpdate')
    ModelVersion = apps.get_model('DESD_App', 'ModelVersion')
    UsageQuota = apps.get_model('DESD_App', 'UsageQuota')
    UsageTracking = apps.get_model('DESD_App', 'UsageTracking')
    AIEngineerRequest = apps.get_model('DESD_App', 'AIEngineerRequest')
    
    ModelPerformance.objects.all().delete()
    ModelUpdate.objects.all().delete()
    ModelVersion.objects.all().delete()
    UsageQuota.objects.all().delete()
    UsageTracking.objects.all().delete()
    AIEngineerRequest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "DESD_App",
            "0003_usagetracking_usagequota_subscription_modelversion_and_more",
        ),
    ]

    operations = [
        # First run a function to delete all data from the tables
        migrations.RunPython(delete_all_data, migrations.RunPython.noop),
        
        # Then remove the fields and models
        migrations.RemoveField(
            model_name="modelperformance",
            name="model_version",
        ),
        migrations.RemoveField(
            model_name="modelupdate",
            name="model_version",
        ),
        migrations.RemoveField(
            model_name="modelupdate",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="modelversion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="modelversion",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="usagequota",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usagetracking",
            name="user",
        ),
        migrations.DeleteModel(
            name="AIEngineerRequest",
        ),
        migrations.DeleteModel(
            name="ModelPerformance",
        ),
        migrations.DeleteModel(
            name="ModelUpdate",
        ),
        migrations.DeleteModel(
            name="ModelVersion",
        ),
        migrations.DeleteModel(
            name="UsageQuota",
        ),
        migrations.DeleteModel(
            name="UsageTracking",
        ),
    ]
