# Generated by Django 4.2.19 on 2025-04-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DESD_App", "0004_delete_userprofile"),
    ]

    operations = []
