# Generated by Django 5.1.3 on 2025-05-01 09:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DESD_App", "0004_remove_unused_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("model_version", models.CharField(max_length=50)),
                ("workout_type", models.IntegerField(default=0)),
                ("avg_prediction_confidence", models.FloatField()),
                ("min_prediction_confidence", models.FloatField()),
                ("max_prediction_confidence", models.FloatField()),
                ("correction_magnitude_avg", models.FloatField()),
                (
                    "stable_prediction_rate",
                    models.FloatField(
                        help_text="% of predictions that remained stable"
                    ),
                ),
                (
                    "avg_response_latency",
                    models.IntegerField(help_text="Average latency in milliseconds"),
                ),
                (
                    "processing_time_per_frame",
                    models.IntegerField(help_text="Processing time in milliseconds"),
                ),
                (
                    "time_to_first_correction",
                    models.IntegerField(
                        help_text="Time in milliseconds until first correction"
                    ),
                ),
                (
                    "frame_processing_rate",
                    models.FloatField(help_text="Frames processed per second"),
                ),
                ("cpu_usage", models.FloatField(blank=True, null=True)),
                ("memory_usage", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "session_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("session_end", models.DateTimeField(blank=True, null=True)),
                (
                    "total_duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("frames_processed", models.IntegerField(default=0)),
                ("corrections_sent", models.IntegerField(default=0)),
                ("workout_type", models.IntegerField(default=0)),
                (
                    "billable_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("subscription_plan", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("platform", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-session_start"],
            },
        ),
    ]
