# Generated by Django 4.2.19 on 2025-04-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DESD_App", "0005_create_customer_group"),
    ]

    operations = []
