# Generated by Django 5.1.3 on 2025-05-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DESD_App", "0005_modelperformancemetric_usagerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("workout", "Workout Classification"),
                            ("pose", "Pose Correction"),
                            ("muscle", "Muscle Activation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("learning_rate", models.FloatField(default=0.001)),
                ("epochs", models.IntegerField(default=100)),
                ("batch_size", models.IntegerField(default=32)),
                ("accuracy", models.FloatField(default=0.0)),
                ("deployed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_trained", models.DateField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deployed", True)),
                        fields=("model_type", "deployed"),
                        name="unique_deployed_model_per_type",
                    )
                ],
                "unique_together": {("model_type", "deployed")},
            },
        ),
    ]
