# Generated by Django 5.1.3 on 2025-05-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DESD_App", "0006_mlmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mlmodel",
            old_name="last_updated",
            new_name="updated_at",
        ),
        migrations.AlterUniqueTogether(
            name="mlmodel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="version",
            field=models.CharField(default="1.0.0", max_length=20),
        ),
    ]
